export function ensureProvenanceTrailStyles(): void {
  if (typeof document === 'undefined' || !document.head) return;
  const styleId = 'autk-provenance-trail-styles';
  if (document.getElementById(styleId)) return;

  const style = document.createElement('style');
  style.id = styleId;
  style.textContent = [
    '.autk-provenance-root{display:flex;flex-direction:column;height:100%;font-family:system-ui,sans-serif;font-size:13px;gap:10px;min-height:0}',
    '.autk-provenance-toolbar{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}',
    '.autk-provenance-toolbar-main{display:flex;align-items:center;gap:6px;flex-wrap:wrap}',
    '.autk-provenance-toolbar-hint{font-size:11px;color:#5c7389}',
    '.autk-provenance-toggle{padding:6px 10px;border:1px solid #c3cfdb;border-radius:6px;background:#fff;cursor:pointer;font-size:12px;color:#1f344b}',
    '.autk-provenance-toggle:hover{background:#f2f7fd}',
    '.autk-provenance-toggle:disabled{opacity:.55;cursor:not-allowed}',
    '.autk-provenance-graph-wrap{position:relative;border:1px solid #dbe5f0;border-radius:8px;background:#fff;overflow:auto;min-height:280px;height:280px;max-height:360px;cursor:zoom-in}',
    '.autk-provenance-graph-svg{display:block;min-width:100%;max-width:none}',
    '.autk-provenance-edge{stroke:#b9c8d8;stroke-width:1.4;fill:none}',
    '.autk-provenance-node{cursor:pointer}',
    '.autk-provenance-node-circle{fill:#f8fbff;stroke:#6f8baa;stroke-width:1.5}',
    '.autk-provenance-node-current .autk-provenance-node-circle{fill:#dcecff;stroke:#2f5f96;stroke-width:2}',
    '.autk-provenance-node-label{font-size:11px;fill:#1f344b}',
    '.autk-provenance-node-time{font-size:10px;fill:#5c7389}',
    '.autk-provenance-node-insight-dot{fill:#f59e0b;stroke:#fff;stroke-width:1.5}',
    '.autk-provenance-modal-backdrop{position:fixed;inset:0;background:rgba(15,27,44,.48);z-index:11000;display:flex;align-items:center;justify-content:center;padding:24px}',
    '.autk-provenance-modal{width:min(1200px,95vw);height:min(860px,90vh);display:flex;flex-direction:column;border-radius:12px;overflow:hidden;background:#f8fbff;box-shadow:0 28px 80px rgba(17,31,47,.45)}',
    '.autk-provenance-modal-header{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:12px 14px;background:#fff;border-bottom:1px solid #dbe5f0}',
    '.autk-provenance-modal-title{font-size:14px;font-weight:700;color:#1f344b}',
    '.autk-provenance-modal-controls{display:flex;align-items:center;gap:6px}',
    '.autk-provenance-modal-controls button{padding:6px 10px;border:1px solid #c3cfdb;border-radius:6px;background:#fff;color:#1f344b;cursor:pointer;font-size:12px}',
    '.autk-provenance-modal-controls button:hover{background:#edf5ff}',
    '.autk-provenance-modal-body{padding:12px;display:flex;flex:1;min-height:0}',
    '.autk-provenance-modal-canvas{position:relative;flex:1;min-height:0;border:1px solid #dbe5f0;border-radius:8px;background:#fff;overflow:hidden;cursor:grab;touch-action:none}',
    '.autk-provenance-modal-canvas.autk-provenance-panning{cursor:grabbing}',
    '.autk-provenance-modal-svg{display:block;width:100%;height:100%;min-width:0}',
    '.autk-provenance-path{display:flex;flex-direction:column;gap:2px;border:1px solid #dbe5f0;border-radius:8px;background:#fbfdff;max-height:200px;overflow-y:auto}',
    '.autk-provenance-path-item{display:flex;align-items:center;gap:8px;padding:6px 8px;border-bottom:1px solid #e7eef6;cursor:pointer}',
    '.autk-provenance-path-item:last-child{border-bottom:0}',
    '.autk-provenance-path-item:hover{background:#f1f7ff}',
    '.autk-provenance-path-item-current{background:#e8f2ff;font-weight:600}',
    '.autk-provenance-path-label{flex:1;min-width:0}',
    '.autk-provenance-path-time{color:#5c7389;font-size:11px;white-space:nowrap}',
    '.autk-provenance-buttons{display:flex;gap:6px}',
    '.autk-provenance-buttons button{padding:6px 12px;border:1px solid #c3cfdb;border-radius:6px;background:#fff;cursor:pointer}',
    '.autk-provenance-buttons button:hover:not(:disabled){background:#f2f7fd}',
    '.autk-provenance-buttons button:disabled{opacity:.55;cursor:not-allowed}',
    '.autk-prov-insights-wrap{border:1px solid #dbe5f0;border-radius:8px;background:#fbfdff;overflow-y:auto;max-height:420px;min-height:0}',
    '.autk-prov-insights-header{display:flex;align-items:center;justify-content:space-between;padding:8px 10px;border-bottom:1px solid #e7eef6;cursor:pointer;user-select:none}',
    '.autk-prov-insights-header-label{font-size:12px;font-weight:700;color:#1f344b;letter-spacing:.02em}',
    '.autk-prov-insights-chevron{font-size:11px;color:#5c7389}',
    '.autk-prov-insights-body{padding:8px 10px;display:flex;flex-direction:column;gap:10px}',
    '.autk-prov-insights-metrics{display:flex;align-items:center;gap:8px;flex-wrap:wrap}',
    '.autk-prov-strategy-badge{display:inline-block;padding:3px 8px;border-radius:20px;font-size:11px;font-weight:700;color:#fff;white-space:nowrap}',
    '.autk-prov-metrics-meta{font-size:11px;color:#5c7389}',
    '.autk-prov-insights-section{display:flex;flex-direction:column;gap:5px}',
    '.autk-prov-insights-section-title{font-size:11px;font-weight:700;color:#5c7389;text-transform:uppercase;letter-spacing:.05em}',
    '.autk-prov-annotation-textarea{width:100%;padding:6px 8px;border:1px solid #c3cfdb;border-radius:6px;font-family:inherit;font-size:12px;resize:vertical;color:#1f344b;background:#fff;box-sizing:border-box}',
    '.autk-prov-annotation-textarea:focus{outline:none;border-color:#2f5f96}',
    '.autk-prov-annotation-save{align-self:flex-start;padding:5px 10px;border:1px solid #c3cfdb;border-radius:6px;background:#fff;cursor:pointer;font-size:12px;color:#1f344b}',
    '.autk-prov-annotation-save:hover:not(:disabled){background:#edf5ff;border-color:#2f5f96;color:#2f5f96}',
    '.autk-prov-annotation-save:disabled{opacity:.5;cursor:not-allowed}',
    '.autk-prov-freq-group-label{font-size:11px;color:#1f344b;font-weight:600;margin-top:2px}',
    '.autk-prov-freq-row{display:flex;align-items:center;gap:6px;min-height:18px}',
    '.autk-prov-freq-id{font-size:11px;color:#5c7389;width:48px;flex-shrink:0;font-variant-numeric:tabular-nums}',
    '.autk-prov-freq-bar-wrap{flex:1;height:8px;background:#e7eef6;border-radius:4px;overflow:hidden}',
    '.autk-prov-freq-bar-fill{height:100%;background:#2f5f96;border-radius:4px;transition:width .3s}',
    '.autk-prov-freq-count{font-size:11px;color:#1f344b;width:26px;text-align:right;flex-shrink:0}',
    '.autk-prov-anno-item{padding:6px 8px;border-radius:6px;border:1px solid #e7eef6;background:#fff;cursor:pointer}',
    '.autk-prov-anno-item:hover{background:#f1f7ff}',
    '.autk-prov-anno-step{font-size:10px;color:#5c7389;margin-bottom:2px}',
    '.autk-prov-anno-text{font-size:12px;color:#1f344b;line-height:1.4}',
    '.autk-prov-summary-text{margin:0;padding:8px;background:#f0f5fb;border:1px solid #dbe5f0;border-radius:6px;font-size:11px;color:#1f344b;white-space:pre-wrap;word-break:break-word;line-height:1.55;max-height:180px;overflow-y:auto}',
    '.autk-prov-copy-btn{align-self:flex-start;padding:5px 10px;border:1px solid #c3cfdb;border-radius:6px;background:#fff;cursor:pointer;font-size:12px;color:#1f344b}',
    '.autk-prov-copy-btn:hover{background:#edf5ff}',
  ].join('');
  document.head.appendChild(style);
}
