export function ensureInsightsWorkspaceStyles(): void {
  if (typeof document === 'undefined' || !document.head) return;
  const styleId = 'autk-insights-workspace-styles';
  if (document.getElementById(styleId)) return;

  const style = document.createElement('style');
  style.id = styleId;
  style.textContent = [
    '.autk-insights-workspace{display:flex;flex-direction:column;gap:14px;font-family:system-ui,sans-serif;color:#1b3148}',
    '.autk-workspace-header{padding:14px 18px;border:1px solid #d4dde7;border-radius:12px;background:linear-gradient(180deg,#fff,#f6f9fc);box-shadow:0 8px 24px rgba(28,53,76,.09)}',
    '.autk-workspace-header h1{margin:0;font-size:22px;line-height:1.2;color:#1d3b5c}',
    '.autk-workspace-header p{margin:4px 0 0;font-size:12px;color:#546b80}',
    '.autk-workspace-layout{display:grid;grid-template-columns:minmax(360px,1fr) minmax(420px,1fr);gap:14px;align-items:stretch}',
    '.autk-workspace-panel{border:1px solid #d4dde7;border-radius:12px;background:#fff;box-shadow:0 8px 24px rgba(28,53,76,.09);overflow:hidden;min-height:0}',
    '.autk-workspace-panel-header{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px 12px;border-bottom:1px solid #d4dde7;background:linear-gradient(180deg,#fff,#f6f9fc)}',
    '.autk-workspace-panel-header-main{display:flex;flex-direction:column;gap:2px;min-width:0}',
    '.autk-workspace-panel-title{font-size:13px;font-weight:600}',
    '.autk-workspace-panel-hint{font-size:11px;color:#546b80;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
    '.autk-workspace-select-wrap{display:flex;align-items:center;gap:6px;font-size:11px;color:#546b80}',
    '.autk-workspace-select{padding:4px 8px;border:1px solid #d4dde7;border-radius:6px;background:#fff;color:#1b3148;font:inherit}',
    '.autk-workspace-map-panel,.autk-workspace-side-panel{min-height:680px;display:flex;flex-direction:column}',
    '.autk-workspace-map-body{flex:1;min-height:0;display:flex;align-items:stretch;justify-content:center;overflow:hidden;background:#c8dae6}',
    '.autk-workspace-map-body canvas{display:block;width:100%;height:100%}',
    '.autk-workspace-tabbar{display:flex;border-bottom:1px solid #d4dde7;background:#f6f9fc}',
    '.autk-workspace-tab{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;padding:12px;border:none;border-bottom:3px solid transparent;background:transparent;color:#546b80;font:600 12px system-ui,sans-serif;cursor:pointer}',
    '.autk-workspace-tab.active{color:#2f5f96;border-bottom-color:#2f5f96;background:#fff}',
    '.autk-workspace-tab-label{font-size:14px;font-weight:700;color:inherit}',
    '.autk-workspace-tab-meta{font-size:11px;font-weight:500;color:#6d8398;line-height:1.3}',
    '.autk-workspace-badge{font-weight:500;font-size:11px}',
    '.autk-workspace-tab-content{flex:1;min-height:0;display:flex;flex-direction:column;overflow:hidden}',
    '.autk-workspace-hidden{display:none}',
    '.autk-workspace-plot-grid{flex:1;min-height:0;display:grid;grid-template-columns:1fr 1fr;grid-template-rows:1fr 1fr;gap:10px;padding:10px}',
    '.autk-workspace-plot-card{display:flex;flex-direction:column;min-height:0;border:1px solid #d4dde7;border-radius:10px;overflow:hidden;background:#fff}',
    '.autk-workspace-plot-header{cursor:zoom-in}',
    '.autk-workspace-expand-btn{padding:5px 10px;border:1px solid #d4dde7;border-radius:999px;background:#fff;color:#2f5f96;font:600 11px system-ui,sans-serif;cursor:pointer}',
    '.autk-workspace-plot-body{position:relative;flex:1;min-height:0;overflow:hidden}',
    '.autk-workspace-plot-body-inner{position:absolute;inset:0}',
    '.autk-workspace-provenance-grid{flex:1;min-height:0;display:grid;grid-template-columns:minmax(0,1.7fr) minmax(280px,1fr);gap:10px;padding:10px}',
    '.autk-workspace-provenance-main,.autk-workspace-provenance-side{min-height:0;overflow:hidden}',
    '.autk-workspace-trail{height:100%;display:flex;flex-direction:column;min-height:0}',
    '.autk-workspace-insights-slot{height:100%;min-height:0;overflow:auto}',
    '.autk-workspace-session-insights{display:flex;flex-direction:column}',
    '.autk-workspace-session-insights-body{padding:0;min-height:0}',
    '.autk-workspace-bottom-insights{border-top:1px solid #e7eef6}',
    '.autk-session-insights-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0}',
    '.autk-session-insights-card{min-height:220px;padding:16px;border-right:1px solid #dbe5f0;display:flex;flex-direction:column;gap:12px}',
    '.autk-session-insights-card:last-child{border-right:none}',
    '.autk-session-insights-card-title{font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#5c7389}',
    '.autk-session-insights-card-body{flex:1;display:flex;flex-direction:column;gap:8px;min-height:0}',
    '.autk-session-insights-step{font-size:12px;font-weight:600;color:#49627a}',
    '.autk-session-insights-label{font-size:12px;color:#5c7389}',
    '.autk-session-strategy-badge{display:inline-block;align-self:flex-start;padding:4px 12px;border-radius:999px;font-size:12px;font-weight:700;color:#fff}',
    '.autk-session-strategy-desc{font-size:12px;line-height:1.5;color:#4d6479}',
    '.autk-session-metrics-row{display:flex;flex-wrap:wrap;gap:8px}',
    '.autk-session-metric-chip{padding:4px 10px;border:1px solid #dbe5f0;border-radius:8px;background:#f6f9fc;font-size:11px;color:#1f344b}',
    '.autk-session-metric-chip strong{font-weight:700}',
    '.autk-session-annotation-textarea{width:100%;min-height:88px;flex:1;padding:8px 10px;border:1px solid #c3cfdb;border-radius:8px;background:#fff;color:#1f344b;font:inherit;font-size:12px;resize:vertical;box-sizing:border-box}',
    '.autk-session-annotation-textarea:focus{outline:none;border-color:#2f5f96}',
    '.autk-session-button{align-self:flex-start;padding:7px 14px;border:1px solid #c3cfdb;border-radius:8px;background:#fff;color:#1f344b;font:inherit;cursor:pointer}',
    '.autk-session-button:hover:not(:disabled){background:#edf5ff;border-color:#2f5f96;color:#2f5f96}',
    '.autk-session-button:disabled{opacity:.45;cursor:not-allowed}',
    '.autk-session-frequency-scroll{display:flex;flex-direction:column;gap:10px;overflow:auto;min-height:0}',
    '.autk-session-frequency-empty{font-size:12px;color:#5c7389}',
    '.autk-session-frequency-group{display:flex;flex-direction:column;gap:6px}',
    '.autk-session-frequency-group-title{font-size:11px;font-weight:700;color:#1f344b}',
    '.autk-session-frequency-row{display:flex;align-items:center;gap:8px;min-height:18px}',
    '.autk-session-frequency-id{width:112px;flex-shrink:0;font-size:11px;color:#5c7389;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
    '.autk-session-frequency-bar{flex:1;height:8px;border-radius:999px;background:#e7eef6;overflow:hidden}',
    '.autk-session-frequency-fill{height:100%;background:#2f5f96;border-radius:999px}',
    '.autk-session-frequency-count{width:26px;flex-shrink:0;text-align:right;font-size:11px;color:#1f344b}',
    '.autk-session-summary{margin:0;padding:10px;border:1px solid #dbe5f0;border-radius:8px;background:#f0f5fb;white-space:pre-wrap;word-break:break-word;line-height:1.6;font-size:11px;color:#1f344b;overflow:auto;min-height:0;max-height:170px}',
    '.autk-chart-modal-backdrop{position:fixed;inset:0;z-index:12000;display:flex;align-items:center;justify-content:center;padding:24px;background:rgba(14,24,36,.56)}',
    '.autk-chart-modal{width:min(1320px,96vw);height:min(900px,92vh);display:flex;flex-direction:column;overflow:hidden;border-radius:16px;border:1px solid rgba(212,221,231,.85);background:linear-gradient(180deg,#f9fcff,#f3f8fd);box-shadow:0 32px 90px rgba(13,26,40,.45)}',
    '.autk-chart-modal-header{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:14px 16px;border-bottom:1px solid #d4dde7;background:rgba(255,255,255,.92)}',
    '.autk-chart-modal-heading{display:flex;flex-direction:column;gap:3px;min-width:0}',
    '.autk-chart-modal-title{font-size:15px;font-weight:700}',
    '.autk-chart-modal-subtitle{font-size:12px;color:#546b80}',
    '.autk-chart-modal-controls{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}',
    '.autk-chart-modal-controls button{padding:7px 10px;border:1px solid #d4dde7;border-radius:8px;background:#fff;color:#1b3148;font:inherit;cursor:pointer}',
    '.autk-chart-modal-body{flex:1;display:flex;min-height:0;padding:14px}',
    '.autk-chart-modal-canvas{position:relative;flex:1;min-width:0;min-height:0;overflow:hidden;border:1px solid #d4dde7;border-radius:12px;background:linear-gradient(90deg,rgba(207,220,232,.35) 1px,transparent 1px) 0 0 / 32px 32px,linear-gradient(rgba(207,220,232,.35) 1px,transparent 1px) 0 0 / 32px 32px,#fff}',
    '.autk-chart-modal-stage{position:absolute;left:0;top:0;transform-origin:0 0;will-change:transform}',
    '.autk-chart-modal-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 14px 14px;font-size:12px;color:#546b80}',
    '@media (max-width:1260px){.autk-session-insights-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.autk-session-insights-card:nth-child(2){border-right:none}.autk-session-insights-card:nth-child(-n+2){border-bottom:1px solid #dbe5f0}}',
    '@media (max-width:1200px){.autk-workspace-layout{grid-template-columns:1fr}.autk-workspace-provenance-grid{grid-template-columns:1fr}.autk-workspace-map-panel,.autk-workspace-side-panel{min-height:520px}}',
    '@media (max-width:760px){.autk-workspace-plot-grid{grid-template-columns:1fr;grid-template-rows:repeat(4,280px)}.autk-chart-modal{width:96vw;height:92vh}.autk-chart-modal-header,.autk-chart-modal-footer{flex-direction:column;align-items:flex-start}.autk-session-insights-grid{grid-template-columns:1fr}.autk-session-insights-card{border-right:none;border-bottom:1px solid #dbe5f0}.autk-session-insights-card:last-child{border-bottom:none}}',
  ].join('');
  document.head.appendChild(style);
}
